#include "human.h"
#include <cstring>
int main(){
    human* humans= new human[5];
    human*& rhumans=humans;
    strcpy(rhumans[0].name,"zilong");
    rhumans[0].family=new char[30];
    strcpy(rhumans[0].family,"abcd");
    rhumans[0].n_code=12340;
    rhumans[0].age=21;
    strcpy(rhumans[1].name,"Aamon");
    rhumans[1].family=new char[30];
    strcpy(rhumans[1].family,"efgh");
    rhumans[1].n_code=12341;
    rhumans[1].age=23;
    strcpy(rhumans[2].name,"saber");
    rhumans[2].family=new char[30];
    strcpy(rhumans[2].family,"ijkl");
    rhumans[2].n_code=12342;
    rhumans[2].age=26;
    strcpy(rhumans[3].name,"alucard");
    rhumans[3].family=new char[30];
    strcpy(rhumans[3].family,"mnop");
    rhumans[3].n_code=12343;
    rhumans[3].age=24;
    strcpy(rhumans[4].name,"yin");
    rhumans[4].family=new char[30];
    strcpy(rhumans[4].family,"qrst");
    rhumans[4].n_code=12344;
    rhumans[4].age=19;
    student* students=new student[5];
    student*& rstudents=students;
    strcpy(rstudents[0].h.name,"dyrroth");
    rstudents[0].h.family=new char[30];
    strcpy(rstudents[0].h.family,"aaaa");
    rstudents[0].h.n_code=12345;
    rstudents[0].h.age=18;
    strcpy(rstudents[0].field,"Computer Engineering");
    rstudents[0].std_no=98760;
    rstudents[0].avg=19.2;
    strcpy(rstudents[1].h.name,"thamuz");
    rstudents[1].h.family=new char[30];
    strcpy(rstudents[1].h.family,"bbbb");
    rstudents[1].h.n_code=12346;
    rstudents[1].h.age=30;
    strcpy(rstudents[1].field,"Civil Engineering");
    rstudents[1].std_no=98761;
    rstudents[1].avg=17.68;
    strcpy(rstudents[2].h.name,"terzila");
    rstudents[2].h.family=new char[30];
    strcpy(rstudents[2].h.family,"cccc");
    rstudents[2].h.n_code=12347;
    rstudents[2].h.age=38;
    strcpy(rstudents[2].field,"Mechanical Engineering");
    rstudents[2].std_no=98762;
    rstudents[2].avg=17.58;
    strcpy(rstudents[3].h.name,"julian");
    rstudents[3].h.family=new char[30];
    strcpy(rstudents[3].h.family,"dddd");
    rstudents[3].h.n_code=12348;
    rstudents[3].h.age=27;
    strcpy(rstudents[3].field,"Electrical Engineering");
    rstudents[3].std_no=98763;
    rstudents[3].avg=19.4;
    strcpy(rstudents[4].h.name,"hanzo");
    rstudents[4].h.family=new char[30];
    strcpy(rstudents[4].h.family,"dddd");
    rstudents[4].h.n_code=12349;
    rstudents[4].h.age=31;
    strcpy(rstudents[4].field,"phsyic");
    rstudents[4].std_no=98764;
    rstudents[4].avg=19.1;
    target_sec(rhumans,5);
    target_sec(rstudents,5);
    int second_max=-1;
    bool B=true;
    target_sec(rstudents,5,B);
    B=false;
    target_sec(rstudents,5,B);
    deletedn(rstudents,5);
    deletedn(rhumans,5);
    return 0;
    //mitavan meghdar bool ra be soorat pish farz baraye function gharar dad da insoorat hengam farakhani function bool be soorat deafult barabar ba false mishavad.
}